baseURL = "http://arcatelier.github.io/"
languageCode = "en-us"
title = "arcatelier"
theme = "autophugo"
paginate     = 10

# https://grep.app/search?q=dark&regexp=true&case=true&filter%5Bpath.pattern%5D%5B0%5D=config.toml
# ga dark config.toml
mode = "dark" # "dark", "auto", "light"  

[markup.goldmark.renderer]
unsafe= true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Art, Design and Infrastructure."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Art, Design and Infrastructure"
  keywords = "NLP, GPT-3"
  images = [""]

  [params.portrait]
    path        = "images/arcatelier.png"
    maxwidth        = "7em"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "arcatelier"
    subtitle = "Art, Design and Infrastructure"
    keywords = "art"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "arcatelier"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about/"

  [[menu.main]]
    identifier = "art"
    name       = "art"
    url        = "/art/"

  [[menu.main]]
    identifier = "infrastructure"
    name       = "infrastructure"
    url        = "/infrastructure/"